### ISSUE TITLE
Snapshots are not being published to Sonatype

### ISSUE THREAD

**Issue by elliottpope** [micronaut-projects/micronaut-jms#115]
### Task List

- [x] Steps to reproduce provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Commit to the `master` branch
2. See the `Java 8` GitHub Action fail ([most recent run](https://github.com/micronaut-projects/micronaut-jms/runs/2763949984))

### Expected Behaviour

All GitHub Actions should pass on commit to `master`

### Actual Behaviour

`Java 8` GitHub Action fails on `master` only during the `Publish to Sonatype Snapshots`

**Comment by elliottpope** [comment]
@burtbeckwith I'm not super familiar with Micronaut's build/release ecosystem so any help you could give here would be greatly appreciated

**Comment by graemerocher** [comment]
Normally these errors are because the POM is somehow invalid

**Comment by graemerocher** [comment]
Seems it has been failing since https://github.com/micronaut-projects/micronaut-jms/commit/56dc69757fa34fce958b02359b899e124f9738d5 

any ideas @burtbeckwith ?
