### ISSUE TITLE
Add support for AWS SDK v2

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-jms#35]
See https://micronaut-projects.github.io/micronaut-aws/latest/guide/index.html#sqs

**Comment by burtbeckwith** [comment]
I looked into it, but there's currently no SQS JMS support in V2 - see https://github.com/aws/aws-sdk-java-v2/issues/1374

**Comment by alvarosanchez** [comment]
Good catch! Closing this.

**Comment by akefirad** [comment]
@burtbeckwith Do you mind opening the issue? https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.0.0

**Comment by charlie-harvey** [comment]
Up to 2.0.3 now!

https://github.com/awslabs/amazon-sqs-java-messaging-lib/releases/tag/2.0.3

**Comment by charlie-harvey** [comment]
I made a PR!

https://github.com/micronaut-projects/micronaut-jms/pull/329

**Comment by charlie-harvey** [comment]
Struggling to get my PR to build. Exception in the tests. But I can't figure out how to get the stack trace to see what is actually wrong. I have the same JDK and Graal on my macbook. No idea what could be wrong.

So close though...
