### ISSUE TITLE
SQS does not support message selector, but micronaut defaults to empty string

### ISSUE THREAD

**Issue by samu-developments** [micronaut-projects/micronaut-jms#439]
### Expected Behavior

Consuming from SQS queue should work.

### Actual Behaviour

@Queue annotation defaults messageSelector to ""
https://github.com/micronaut-projects/micronaut-jms/blob/9c77b572519bb463b5b409fb8ef556f46a23547f/jms-core/src/main/java/io/micronaut/jms/annotations/Queue.java#L134 

AWS sdk is not happy about non null message selector:
```
if (messageSelector != null) {
            throw new JMSException("SQSSession does not support MessageSelector. This should be null.");
```
https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/4cb91355cb92d9361a2179233c9db89383b1299e/src/main/java/com/amazon/sqs/javamessaging/SQSSession.java#L572

AWS sdk is likely not adding this in the foreseeable future.. https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/4

### Steps To Reproduce

```
import io.micronaut.jms.annotations.JMSListener
import io.micronaut.jms.annotations.Queue
import io.micronaut.jms.sqs.configuration.SqsConfiguration.CONNECTION_FACTORY_BEAN_NAME
import io.micronaut.messaging.annotation.MessageBody

@JMSListener(CONNECTION_FACTORY_BEAN_NAME)
class TestConsumer {
    @Queue(value = "test_queue")
    fun receive(@MessageBody test: String) = println("received : $test")
}
``` 

### Version

core: 4.1.8, jms: 3.0.1

**Comment by samu-developments** [comment]
Example application: 
https://github.com/samu-developments/sqs-mn-issue

To test it you need a SQS queue in AWS named "test_queue", and run the application with valid AWS credentials so the application can talk to SQS.

**Comment by sreejithvs1** [comment]
When could we expect a fix for this ? I cant even pass null for the value in annotation

**Comment by liefra** [comment]
@samu-developments : Facing the same issue. Are you maybe aware of any workaround for now?

**Comment by samu-developments** [comment]
> @samu-developments : Facing the same issue. Are you maybe aware of any workaround for now?

Yes, I just built the project with the fix from https://github.com/micronaut-projects/micronaut-jms/pull/440 and copy the jms-core jar to `projectRoot/libs` folder. Then in build.gradle.kts:

```
implementation(files("libs/micronaut-jms-core-3.0.2-SNAPSHOT.jar"))
```

**Comment by liefra** [comment]
Nice. Thank you for sharing this workaround.

**Comment by cdome** [comment]
The problem here seems to be ```ksp``` annotation processor. It works properly with ```kapt``` (so - you can use it as a workaround).

The thing is that when MN registers annotation default values in ```AnnotationMetadataSupport.registerAnnotationDefaults()```, these default values come from the annotation processor. Kapt returns null for a default value of empty string, while Ksp returns empty string as default value. Thus then - under Kapt, null gets propagated to ```SQSSession.createConsumer``` and it works and under Ksp it's empty string which gets there and it doesnt work because AWS implementation thinks the ```messageSelector``` is defined...
