### ISSUE TITLE
Enable setting of TTL

### ISSUE THREAD

**Issue by jaecktec** [micronaut-projects/micronaut-jms#462]
### Feature description

This issue is basically just a ping to follow up on that [TODO](https://github.com/micronaut-projects/micronaut-jms/blob/02fc6d87d98a0fad7daf951085d38198eb3077fe/jms-core/src/main/java/io/micronaut/jms/templates/JmsProducer.java#L198)

I'd also be willing to implement this. 
Anything I would need to take care of when implementing it?

**Comment by jaecktec** [comment]
This could be implemented as just another `JMSProducer` or `Queue` property (pretty simple I guess) - If this should be configurable I think it might be more complicated, since we'd need to have another annotation. 

I'm not sure how useful a variable timeout would be, for me a static timeout would be fine

**Comment by sdelamo** [comment]
@jaecktec if you are interested in contributing a PR that it is great.
